In [2]:
# 1. Using Ufuncs
# You can use ufuncs by simply applying them to a NumPy array. Here are some examples:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Applying ufuncs to the array
square_arr = np.square(arr)   # Element-wise square
sqrt_arr = np.sqrt(arr)       # Element-wise square root
exp_arr = np.exp(arr)         # Element-wise exponential
log_arr = np.log(arr)         # Element-wise natural logarithm

print(square_arr)
print(sqrt_arr)
print(exp_arr)
print(log_arr)


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [3]:
# 2. Broadcasting with Ufuncs
# Ufuncs also work seamlessly with broadcasting, as we discussed in a previous lesson. Broadcasting allows ufuncs to operate on arrays with different shapes or sizes, making your code more concise and efficient when dealing with multi-dimensional arrays.

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 2, 2])

# Broadcasting with ufuncs
result = np.power(arr1, arr2)  # Element-wise power operation

print(result)  # Output: [1 4 9]


[1 4 9]
