In [1]:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenate along axis 0 (rows)
concatenated_rows = np.concatenate((arr1, arr2), axis=0)

# Concatenate along axis 1 (columns)
concatenated_columns = np.concatenate((arr1, arr2), axis=1)  # Raises an error for 1D arrays

print(concatenated_rows)
print(concatenated_columns)


AxisError: axis 1 is out of bounds for array of dimension 1

In [2]:
# For multi-dimensional arrays, you can concatenate along any axis as long as the dimensions match:

import numpy as np

# Create two 2D arrays
arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

# Concatenate along axis 0 (rows)
concatenated_rows = np.concatenate((arr1, arr2), axis=0)

# Concatenate along axis 1 (columns)
concatenated_columns = np.concatenate((arr1, arr2), axis=1)

print(concatenated_rows)
print(concatenated_columns)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
