In [1]:
# 1. numpy.sin and numpy.cos
# These functions calculate the sine and cosine of each element in an array. They are often used in trigonometric calculations.


import numpy as np

arr = np.array([0, np.pi/4, np.pi/2])

sin_arr = np.sin(arr)
cos_arr = np.cos(arr)

print(sin_arr)  # Output: [0.         0.70710678 1.        ]
print(cos_arr)  # Output: [1.00000000e+00 7.07106781e-01 6.12323400e-17]


[0.         0.70710678 1.        ]
[1.00000000e+00 7.07106781e-01 6.12323400e-17]


In [2]:
# 2. numpy.exp and numpy.log
# These functions calculate the exponential and natural logarithm of each element in an array. Exponential functions are often used in growth models, while logarithmic functions are used in various calculations and data transformations.

import numpy as np

arr = np.array([1, 2, 3])

exp_arr = np.exp(arr)
log_arr = np.log(arr)

print(exp_arr)  # Output: [ 2.71828183  7.3890561  20.08553692]
print(log_arr)  # Output: [0.         0.69314718 1.09861229]


[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]


In [3]:
# 3. numpy.sqrt
# The numpy.sqrt function calculates the square root of each element in an array.

import numpy as np

arr = np.array([4, 9, 16])

sqrt_arr = np.sqrt(arr)

print(sqrt_arr)  # Output: [2. 3. 4.]


[2. 3. 4.]


In [4]:
# 4. numpy.power
# The numpy.power function raises each element in an array to a specified power.

import numpy as np

arr = np.array([1, 2, 3])

power_arr = np.power(arr, 2)

print(power_arr)  # Output: [1 4 9]


[1 4 9]
