In [1]:
# 1. numpy.sum
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all elements
total_sum = np.sum(arr)

# Sum along rows (axis=0)
row_sum = np.sum(arr, axis=0)

# Sum along columns (axis=1)
col_sum = np.sum(arr, axis=1)

print(total_sum)  # Output: 21
print(row_sum)    # Output: [5 7 9]
print(col_sum)    # Output: [ 6 15]


21
[5 7 9]
[ 6 15]


In [2]:
# 2.numpy.mean

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Mean of all elements
average = np.mean(arr)

# Mean along rows (axis=0)
row_average = np.mean(arr, axis=0)

# Mean along columns (axis=1)
col_average = np.mean(arr, axis=1)

print(average)    # Output: 3.5
print(row_average)  # Output: [2.5 3.5 4.5]
print(col_average)  # Output: [2. 5.]


3.5
[2.5 3.5 4.5]
[2. 5.]


In [3]:
# 3.numpy.std

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Standard deviation of all elements
std_deviation = np.std(arr)

# Standard deviation along rows (axis=0)
row_std_deviation = np.std(arr, axis=0)

# Standard deviation along columns (axis=1)
col_std_deviation = np.std(arr, axis=1)

print(std_deviation)       # Output: 1.707825127659933
print(row_std_deviation)   # Output: [1.5 1.5 1.5]
print(col_std_deviation)   # Output: [0.81649658 0.81649658]


1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]
