In [4]:
# Creating Arrays using NumPy
import numpy as np

# 1. Using numpy.array
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)

# Using numpy.zeros
zeros_array = np.zeros((3, 4))
print(zeros_array)

# Using numpy.ones
ones_array = np.ones((2, 3))
print(ones_array)

# Using numpy.arrange:
range_array = np.arange(0, 10, 2)
print(range_array)



[1 2 3 4 5]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
