In [1]:
# 1. Unique Values
# To find unique values in an array, you can use numpy.unique:

import numpy as np

arr = np.array([1, 2, 2, 3, 3, 4, 5])

unique_values = np.unique(arr)

print(unique_values)  # Output: [1 2 3 4 5]


[1 2 3 4 5]


In [2]:
# 2. Value Counts
# To find the count of each unique value in an array, you can use numpy.unique with the return_counts=True parameter:

import numpy as np

arr = np.array([1, 2, 2, 3, 3, 4, 5])

unique_values, value_counts = np.unique(arr, return_counts=True)

print(unique_values)    # Output: [1 2 3 4 5]
print(value_counts)     # Output: [1 2 2 1 1]


[1 2 3 4 5]
[1 2 2 1 1]
