In [1]:
# Basic Element-wise Arithmetic Operations

import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
result_add = arr1 + arr2

# Element-wise subtraction
result_subtract = arr1 - arr2

# Element-wise multiplication
result_multiply = arr1 * arr2

# Element-wise division
result_divide = arr1 / arr2

print(result_add)       # [5 7 9]
print(result_subtract)  # [-3 -3 -3]
print(result_multiply)  # [ 4 10 18]
print(result_divide)    # [0.25 0.4  0.5 ]


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
