In [1]:
# In this case, the scalar value 2 is broadcasted to match the shape of arr1, and element-wise multiplication is performed
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 2

# Multiply the array by a scalar
result = arr1 * scalar

print(result)


[[ 2  4  6]
 [ 8 10 12]]


In [2]:
# In this case, arr2 with shape (3,) is broadcasted to match the shape of arr1, and element-wise multiplication is performed.
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

# Multiply arrays with different shapes
result = arr1 * arr2

print(result)


[[ 10  40  90]
 [ 40 100 180]]
